import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Volume2} from 'lucide-react';
import type {Language} from './types';
import {locales,text} from './language';
type Recognition={lang:string;interimResults:boolean;continuous:boolean;onresult:((e:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void};
export function VoiceInput({language,onText,onAudio}:{language:Language;onText:(s:string)=>void;onAudio?:(s:string)=>void}){
 const[active,setActive]=useState(false),[note,setNote]=useState(''),[recording,setRecording]=useState(false);const rec=useRef<Recognition|null>(null),media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null);
 useEffect(()=>()=>{rec.current?.stop();if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());},[]);
 function start(){const W=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const C=W.SpeechRecognition||W.webkitSpeechRecognition;if(!C){setNote('This browser cannot transcribe speech. Type your symptoms or save a voice note below.');return}if(!navigator.onLine){setNote('Offline transcription is not available here. Save a voice note or type your symptoms.');return}const r=new C();rec.current=r;r.lang=locales[language];r.interimResults=false;r.continuous=false;r.onresult=e=>{onText(Array.from(e.results).map(x=>x[0].transcript).join(' '));setNote('Review and correct the text before continuing.');};r.onerror=e=>{setNote('Microphone/transcription unavailable: '+e.error+'. You can type instead.');setActive(false)};r.onend=()=>setActive(false);try{r.start();setActive(true)}catch{setNote('Could not start microphone. Please try again.')}}
 async function record(){try{if(recording){media.current?.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Audio recording is not supported in this browser.');stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const m=new MediaRecorder(stream.current);media.current=m;const chunks:BlobPart[]=[];m.ondataavailable=e=>chunks.push(e.data);m.onstop=()=>{stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);const b=new Blob(chunks,{type:m.mimeType});if(b.size>5*1024*1024){setNote('Voice note is too large. Record a shorter note.');return}const f=new FileReader();f.onload=()=>onAudio?.(String(f.result));f.readAsDataURL(b);setNote('Voice note saved with this observation. Add text or select symptoms for analysis.');};m.start();setRecording(true);setTimeout(()=>{if(m.state==='recording')m.stop()},60000);}catch(e){setNote(e instanceof Error?e.message:'Microphone permission is required.')}}
 return <div className="voice-controls"><button type="button" className="secondary" onClick={()=>active?rec.current?.stop():start()}>{active?<Square size={16}/>:<Mic size={16}/>} {active?text[language].stop:text[language].speak}</button>{onAudio&&<button type="button" className="text-button" onClick={()=>void record()}>{recording?'Stop voice note':'Save a voice note (offline)'}</button>}<small>Browser transcription may send audio to its speech service. Saved voice notes stay on this device.</small>{note&&<p role="status">{note}</p>}</div>;
}
export function Speak({language,content}:{language:Language;content:string}){const[error,setError]=useState('');return <><button className="secondary" type="button" onClick={()=>{if(!('speechSynthesis'in window)){setError('Audio playback is unavailable. Read the text below.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(content);u.lang=locales[language];u.rate=.9;u.onerror=()=>setError('No suitable speech voice is available. Read the text below.');speechSynthesis.speak(u)}}><Volume2 size={17}/>{text[language].listen}</button>{error&&<p role="status">{error}</p>}</>}
